[package]
name = "arc061"
version = "0.1.0"
authors = ["BYAK <byakhee0314@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
